(clear)
(unwatch all)
(load "1 init.clp")
(load "2 solve.clp")
(load "3 check.clp")
(load "4 print.clp")
(load "5 puzzle03.clp")
(assert (phase build-puzzle))
(run)
(assert (phase print-puzzle))
(run)
(assert (phase solve))
(run)
(assert (phase print-puzzle))
(run)
(assert (phase check))
(run)
(assert (phase print-status))
(run)
(assert (phase print-techniques))
(run)
